# -*- coding: utf-8 -*-
"""
Created on Thu Oct 19 08:36:33 2023

@author: townsend.lansburg
"""






seasons = {
'Canada': {'start_day': 165, 'end_day': 279}, 
 'United States of America': {'start_day': 155, 'end_day': 252}, 
 'Bolivia': {'start_day': 303, 'end_day': 79}, 
 'Colombia': {'start_day': 112, 'end_day': 218}, 
 'Ecuador': {'start_day': 324, 'end_day': 174},
 'Peru': {'start_day': 303, 'end_day': 49}, 
 'Argentina': {'start_day': 314, 'end_day': 86},
 'Paraguay': {'start_day': 227, 'end_day': 15},
 'Uruguay': {'start_day': 326, 'end_day': 74}, 
 'Albania': {'start_day': 145, 'end_day': 234}, 
 'Austria': {'start_day': 135, 'end_day': 252},
 'Belgium': {'start_day': 135, 'end_day': 252}, 
 'Bosnia and Herzegovina': {'start_day': 135, 'end_day': 250},
 'Bulgaria': {'start_day': 135, 'end_day': 249},
 'Croatia': {'start_day': 130, 'end_day': 250},
 'Czech Republic': {'start_day': 128, 'end_day': 279}, 
 'France': {'start_day': 135, 'end_day': 252}, 
 'Hungary': {'start_day': 135, 'end_day': 252}, 
 'Italy': {'start_day': 122, 'end_day': 249},
 'Luxembourg': {'start_day': 135, 'end_day': 252}, 
 'North Macedonia': {'start_day': 148, 'end_day': 240}, 
 'Malta': {'start_day': 135, 'end_day': 250}, 
 'Netherlands': {'start_day': 135, 'end_day': 262},
 'Portugal': {'start_day': 104, 'end_day': 252}, 
 'Poland': {'start_day': 142, 'end_day': 249}, 
 'Romania': {'start_day': 132, 'end_day': 250}, 
 'Serbia': {'start_day': 136, 'end_day': 258}, 
 'Slovakia': {'start_day': 128, 'end_day': 277}, 
 'Spain': {'start_day': 104, 'end_day': 241},
 'Slovenia': {'start_day': 117, 'end_day': 250}, 
 'Russia': {'start_day': 131, 'end_day': 259},
 'Belarus': {'start_day': 121, 'end_day': 266},
 'Moldova': {'start_day': 120, 'end_day': 253}, 
 'Ukraine': {'start_day': 120, 'end_day': 255},
 'Georgia': {'start_day': 158, 'end_day': 218}, 
 'Iran': {'start_day': 135, 'end_day': 196},
 'Iraq': {'start_day': 173, 'end_day': 247},
 'Syria': {'start_day': 117, 'end_day': 223},
 'Saudi Arabia': {'start_day': 65, 'end_day': 197}, 
 'Turkey': {'start_day': 97, 'end_day': 249},
 'Afghanistan': {'start_day': 158, 'end_day': 231},
 'Kyrgyzstan': {'start_day': 158, 'end_day': 218}, 
 'Turkmenistan': {'start_day': 158, 'end_day': 218}, 
 'Uzbekistan': {'start_day': 158, 'end_day': 218},
 'China': {'start_day': 140, 'end_day': 250}, 
 'North Korea': {'start_day': 122, 'end_day': 232}, 
 'South Korea': {'start_day': 96, 'end_day': 231}, 
 'Australia': {'start_day': 311, 'end_day': 93}, 
 'New Zealand': {'start_day': 275, 'end_day': 66}, 
 'Bangladesh': {'start_day': 330, 'end_day': 96}, 
 'Nepal': {'start_day': 108, 'end_day': 222},
 'Pakistan': {'start_day': 191, 'end_day': 265},
 'Algeria': {'start_day': 78, 'end_day': 157}, 
 'Egypt': {'start_day': 125, 'end_day': 292}, 
 'Morocco': {'start_day': 78, 'end_day': 187}, 
 'Angola': {'start_day': 288, 'end_day': 65}, 
 'Botswana': {'start_day': 1, 'end_day': 112}, 
 'Congo': {'start_day': 315, 'end_day': 190},
 'Eswatini': {'start_day': 341, 'end_day': 126},
 'Lesotho': {'start_day': 341, 'end_day': 126},
 'Madagascar ': {'start_day': 349, 'end_day': 78},
 'Malawi': {'start_day': 280, 'end_day': 110}, 
 'Mozambique': {'start_day': 341, 'end_day': 81}, 
 'Namibia': {'start_day': 357, 'end_day': 154}, 
 'South Africa': {'start_day': 310, 'end_day': 132},
 'Tanzania - Masika': {'start_day': 79, 'end_day': 187},
 'Tanzania - Msimu': {'start_day': 349, 'end_day': 126}, 
 'Tanzania - Vuli': {'start_day': 288, 'end_day': 4},
 'Zambia': {'start_day': 341, 'end_day': 110}, 
 'Zimbabwe': {'start_day': 349, 'end_day': 126}, 
 'Burundi': {'start_day': 270, 'end_day': 30}, 
 'Ethiopia': {'start_day': 148, 'end_day': 268}, 
 'Eritrea': {'start_day': 196, 'end_day': 308}, 
 'Uganda - North': {'start_day': 135, 'end_day': 218},
 'Burkina Faso': {'start_day': 158, 'end_day': 224}, 
 'Chad': {'start_day': 196, 'end_day': 249}, 
 'Cabo Verde': {'start_day': 227, 'end_day': 193},
 'Central Africa Republic': {'start_day': 134, 'end_day': 171},
 'Gambia': {'start_day': 188, 'end_day': 249}, 
 'Guinea-Bissau': {'start_day': 165, 'end_day': 249}, 
 'Guinea': {'start_day': 165, 'end_day': 279}, 
 'Mauritania': {'start_day': 227, 'end_day': 279}, 
 'Mali': {'start_day': 188, 'end_day': 252}, 
 'Nigeria': {'start_day': 104, 'end_day': 210}, 
 'Niger': {'start_day': 183, 'end_day': 257},
 'Sierra Leone': {'start_day': 188, 'end_day': 279}, 
 'Senegal': {'start_day': 196, 'end_day': 250}

}


seasons_one =  {
    'Brazil':{ 
    'Maranhao': {"start_day": 300, "end_day": 10},
         'Rio Grande do Sul': {"start_day": 300, "end_day": 10},
         'Parana': {"start_day": 300, "end_day": 10}, 
         'Sao Paulo': {"start_day": 300, "end_day": 10},
         'Minas Gerais': {"start_day": 300, "end_day": 10},
       'Goias': {"start_day": 300, "end_day": 10}, 
       'Mato Grosso': {"start_day": 300, "end_day": 10}, 
       'Mato Grosso do Sul': {"start_day": 300, "end_day": 10}, 
       'Bahia': {"start_day": 300, "end_day": 10}, 
       'Tocantins': {"start_day": 300, "end_day": 10},
       'Santa Catarina': {"start_day": 300, "end_day": 20},
       'Piaui': {"start_day": 300, "end_day": 20},
       'Federal District': {"start_day": 300, "end_day": 20},
       'Espirito Santo': {"start_day": 300, "end_day": 20},
       'Rio de Janeiro':{"start_day": 300, "end_day": 20},
       'Ceara':{"start_day": 300, "end_day": 20},
       'Rio Grande do Norte':{"start_day": 300, "end_day": 20},
       'Paraiba':{"start_day": 300, "end_day": 20},
       'Pernambuco':{"start_day": 300, "end_day": 20},
       'Alagoas':{"start_day": 300, "end_day": 20},
       'Sergipe':{"start_day": 300, "end_day": 20},
         'Rondonia':{"start_day": 300, "end_day": 20},
          'Acre':{"start_day": 300, "end_day": 20},
          'Amazonas':{"start_day": 300, "end_day": 20},
          'Roraima':{"start_day": 300, "end_day": 20},
          'Amapa':{"start_day": 300, "end_day": 20},
         'Para':{"start_day": 300, "end_day": 20},},
    'Mexico': {'start_day': 204, 'end_day': 296}, 
     'Costa Rica': {'start_day': 135, 'end_day': 218},
     'Cuba': {'start_day': 6, 'end_day': 80},
     'Dominican Republic': {'start_day': 127, 'end_day': 190}, 
     'El Salvador': {'start_day': 165, 'end_day': 224}, 
     'Honduras': {'start_day': 165, 'end_day': 246}, 
     'Haiti': {'start_day': 104, 'end_day': 160}, 
     'Guatemala': {'start_day': 135, 'end_day': 160},
     'Panama': {'start_day': 257, 'end_day': 347}, 
     'Nicaragua': {'start_day': 165, 'end_day': 218}, 
     'Brazil ': {'start_day': 341, 'end_day': 46}, 
     'Venezuela': {'start_day': 188, 'end_day': 255},
     'Burma': {'start_day': 212, 'end_day': 6}, 
     'Cambodia': {'start_day': 227, 'end_day': 279}, 
     'Indonesia': {'start_day': 188, 'end_day': 221}, 
     'Philippines': {'start_day': 149, 'end_day': 193}, 
     'Thailand': {'start_day': 212, 'end_day': 255}, 
     'Timor-Leste': {'start_day': 341, 'end_day': 40}, 
     'Vietnam': {'start_day': 44, 'end_day': 110}, 
     'India': {'start_day': 173, 'end_day': 227}, 
     'Sri Lanka': {'start_day': 306, 'end_day': 40}, 
     'Kenya': {'start_day': 130, 'end_day': 280}, 
     'Somalia': {'start_day': 112, 'end_day': 215}, 
     'South Sudan': {'start_day': 104, 'end_day': 210}, 
     'Rwanda': {'start_day': 75, 'end_day': 183}, 
     'Uganda - South': {'start_day': 75, 'end_day': 157},
     'Benin': {'start_day': 104, 'end_day': 218}, 
     'Cameroon': {'start_day': 150, 'end_day': 318},
     "Cote d'Ivoire": {'start_day': 104, 'end_day': 218},
     'Gabon': {'start_day': 288, 'end_day': 343}, 
     'Ghana': {'start_day': 104, 'end_day': 218}, 
     'Togo': {'start_day': 104, 'end_day': 218}}




seasons_two = {'Brazil':{ 
    'Maranhao': {"start_day": 120, "end_day": 175},
         'Rio Grande do Sul': {"start_day": 120, "end_day": 175},
         'Parana': {"start_day": 120, "end_day": 175}, 
         'Sao Paulo': {"start_day": 120, "end_day": 175},
         'Minas Gerais': {"start_day": 120, "end_day": 175},
       'Goias': {"start_day": 120, "end_day": 175}, 
       'Mato Grosso': {"start_day": 105, "end_day": 161}, 
       'Mato Grosso do Sul': {"start_day": 110, "end_day": 170}, 
       'Bahia': {"start_day": 120, "end_day": 170}, 
       'Tocantins': {"start_day": 120, "end_day": 170},
       'Santa Catarina': {"start_day": 120, "end_day": 170},
       'Piaui': {"start_day": 120, "end_day": 170},
       'Federal District': {"start_day": 120, "end_day": 170},
       'Espirito Santo': {"start_day": 120, "end_day": 170},
       'Rio de Janeiro':{"start_day": 120, "end_day": 170},
       'Ceara':{"start_day": 120, "end_day": 170},
       'Rio Grande do Norte':{"start_day": 120, "end_day": 170},
       'Paraiba':{"start_day": 120, "end_day": 170},
       'Pernambuco':{"start_day": 120, "end_day": 170},
       'Alagoas':{"start_day": 120, "end_day": 170},
       'Sergipe':{"start_day": 120, "end_day": 170},
         'Rondonia':{"start_day": 120, "end_day": 170},
          'Acre':{"start_day": 120, "end_day": 170},
          'Amazonas':{"start_day": 120, "end_day": 170},
          'Roraima':{"start_day": 120, "end_day": 170},
          'Amapa':{"start_day": 120, "end_day": 170},
         'Para':{"start_day": 120, "end_day": 170},},
    'Mexico': {'start_day': 16, 'end_day': 102}, 
     'Costa Rica': {'start_day': 257, 'end_day': 318},
     'Cuba': {'start_day': 219, 'end_day': 282}, 
     'Dominican Republic': {'start_day': 300, 'end_day': 90},
     'El Salvador': {'start_day': 265, 'end_day': 34}, 
     'Honduras': {'start_day': 280, 'end_day': 65},
     'Haiti': {'start_day': 227, 'end_day': 365}, 
     'Guatemala': {'start_day': 341, 'end_day': 100}, 
     'Panama': {'start_day': 165, 'end_day': 218},
     'Nicaragua': {'start_day': 270, 'end_day': 60}, 
     'Brazil ': {'start_day': 44, 'end_day': 163}, 
     'Venezuela': {'start_day': 318, 'end_day': 96}, 
     'Burma': {'start_day': 341, 'end_day': 200}, 
     'Cambodia': {'start_day': 75, 'end_day': 157}, 
     'Indonesia': {'start_day': 341, 'end_day': 40}, 
     'Philippines': {'start_day': 333, 'end_day': 45},
     'Thailand': {'start_day': 326, 'end_day': 34},
     'Timor-Leste': {'start_day': 158, 'end_day': 224},
     'Vietnam': {'start_day': 341, 'end_day': 12},
     'India': {'start_day': 318, 'end_day': 65}, 
     'Sri Lanka': {'start_day': 135, 'end_day': 218},
     'Kenya': {'start_day': 318, 'end_day': 63}, 
     'Somalia': {'start_day': 279, 'end_day': 76}, 
     'South Sudan': {'start_day': 257, 'end_day': 343}, 
     'Rwanda': {'start_day': 288, 'end_day': 6}, 
     'Uganda - South': {'start_day': 288, 'end_day': 343}, 
     'Benin': {'start_day': 257, 'end_day': 343},
     "Cote d'Ivoire": {'start_day': 257, 'end_day': 343}, 
     'Gabon': {'start_day': 44, 'end_day': 126},
     'Ghana': {'start_day': 257, 'end_day': 343},
     'Republic of the Congo': {'start_day': 75, 'end_day': 183}, 
     'Togo': {'start_day': 257, 'end_day': 343}}
          
     




state_production = {'United States of America': {'Iowa': 16.0,
  'Illinois': 14.0,
  'Nebraska': 11.0,
  'Minnesota': 9.0,
  'Indiana': 6.0,
  'South Dakota': 5.0,
  'Kansas': 5.0,
  'Missouri': 4.0,
  'Wisconsin': 4.0,
  'Ohio': 3.0,
  'Michigan': 3.0,
  'Kentucky': 2.0,
  'North Dakota': 2.0,
  'Texas': 2.0,
  'Colorado': 2.0,
  'Tennessee': 2.0,
  'Pennsylvania': 2.0,
  'Arkansas': 2.0,
  'Mississippi': 1.0,
  'North Carolina': 1.0},


 "China": {
   "Heilongjiang": 20.0,
   "Jilin": 19.0,
   "Liaoning": 15.0,
   "Inner Mongolia": 13.0,
   "Shandong": 10.0,
   "Henan": 8.0,
   "Hebei": 6.0,
   "Shaanxi": 4.0,
   "Sichuan": 2.5,
   "Yunnan": 1.5,
   "Anhui": 1.0,
   "Hubei": 0.5,
   "Jiangsu": 0.5,
   "Chongqing": 0.5,
   "Guangxi": 0.5,
   "Hunan": 0.5,
   "Beijing": 0.0,
   "Fujian": 0.0,
   "Gansu": 0.0,
   "Guangdong Province": 0.0,
   "Guizhou": 0.0,
   "Hainan Province": 0.0,
   "Jiangxi": 0.0,
   "Macau": 0.0,
   "Ningxia": 0.0,
   "Qinghai": 0.0,
   "Shanxi": 0.0,
   "Tianjin": 0.0,
   "Tibet": 0.0,
   "Xinjiang": 0.0,
   "Zhejiang": 0.0,
   "Hong Kong": 0.0},


 'Brazil': {'Parana': 23.0,
  'Rio Grande do Sul': 17.0,
  'Mato Grosso': 15.0,
  'Sao Paulo': 12.0,
  'Goias': 9.0,
  'Minas Gerais': 6.0,
  'Santa Catarina': 5.0,
  'Bahia': 3.0,
  'Mato Grosso do Sul': 2.0,
  'Maranhao': 2.0,
  'Piaui': 1.0,
  'Federal District': 0.3,
  'Espirito Santo': 0.1,
  'Rio de Janeiro':0.001,
  'Ceara':2.5,
  'Rio Grande do Norte':0.2,
  'Paraiba':0.5,
  'Pernambuco':0.9,
  'Alagoas':0.2,
  'Sergipe':0.8,
    'Rondonia':1.3,
     'Acre':0.2,
     'Amazonas':0.00001,
     'Roraima':0.1,
     'Amapa':0.001,
    'Para':1.8,
     'Tocantins':1.9,},
 
  
  
  





 'Argentina': {'Buenos Aires': 25.0,
  'Cordoba': 25.0,
  'Santa Fe': 20.0,
  'Entre Rios': 10.0,
  'La Pampa': 7.0,
  'Santiago del Estero': 6.0,
  'Tucuman': 4.0,
  'Chaco': 3.0,
},
 
               
               'India': {'Karnataka': 22.0,
  'Andhra Pradesh': 16.0,
  'Maharashtra': 12.0,
  'Bihar': 9.0,
  'Uttar Pradesh': 8.0,
  'Tamil Nadu': 7.0,
  'Rajasthan': 6.0,
  'Madhya Pradesh': 5.0,
  'Telangana': 4.0,
  'Gujarat': 3.0,
  'Haryana': 2.0,
  'Punjab': 2.0,
  'West Bengal': 2.0,
  'Odisha': 2.0,
  'Assam': 1.0},
 
    
    'Mexico': {'Jalisco': 12.0,
  'Sinaloa': 11.0,
  'Michoacan': 10.0,
  'Veracruz': 7.0,
  'Tamaulipas': 7.0,
  'Guanajuato': 5.0,
  'Sonora': 5.0,
  'Puebla': 4.0,
  'Chiapas': 3.0,
  'Nayarit': 3.0,
  'San Luis Potosi': 3.0,
  'Estado de Mexico': 2.0,
  'Queretaro': 2.0,
  'Tabasco': 2.0,
  'Hidalgo': 2.0,
  'Zacatecas': 1.0,
  'Quintana Roo': 1.0,
  'Oaxaca': 1.0,
  'Chihuahua': 1.0,
  'Durango': 1.0},
 
    
               'Ukraine': {'Vinnytsia': 12.0,
  'Kharkiv': 10.0,
  'Poltava': 9.0,
  'Zaporizhzhia': 8.0,
  'Khmelnytskyi': 7.0,
  'Cherkasy': 6.0,
  'Dnipropetrovsk': 6.0,
  'Kyiv': 5.0,
  'Zhytomyr': 5.0,
  'Odessa': 4.0,
  'Mykolaiv': 4.0,
  'Ternopil': 3.0,
  'Lviv': 2.0,
  'Kirovohrad': 2.0,
  'Sumy': 2.0,
  'Rivne': 2.0,
  'Kherson': 2.0,
  'Volyn': 1.0,
  'Ivano-Frankivsk': 1.0,
  'Donetsk': 1.0},


 'South Africa': {'Free State': 23.0,
  'Mpumalanga': 17.0,
  'North West': 14.0,
  'KwaZulu-Natal': 10.0,
  'Gauteng': 7.0,
  'Limpopo': 6.0,
  'Eastern Cape': 5.0,
  'Western Cape': 4.0,
  'Northern Cape': 3.0},
 
                  
                  
                  'Russia': {'Krasnodar Krai': 15.0,
  'Rostov Oblast': 10.0,
  'Stavropol Krai': 8.0,
  'Saratov Oblast': 6.0,
  'Belgorod Oblast': 5.0,
  'Lipetsk Oblast': 5.0,
  'Tambov Oblast': 4.0,
  'Voronezh Oblast': 4.0,
  'Kursk Oblast': 4.0,
  'Altai Krai': 3.0,
  'Samara Oblast': 3.0,
  'Orenburg Oblast': 3.0,
  'Oryol Oblast': 2.0,
  'Penza Oblast': 2.0,
  'Bryansk Oblast': 2.0,
  'Kemerovo Oblast': 2.0,
  'Sverdlovsk Oblast': 2.0,
  'Vologda Oblast': 1.0,
  'Tyumen Oblast': 1.0,
  'Kostroma Oblast': 1.0},


 'France': {'Occitanie': 13.0,
  'Nouvelle-Aquitaine': 11.0,
  'Centre-Val de Loire': 9.0,
  'Pays de la Loire': 8.0,
  'Bourgogne-Franche-Comte': 7.0,
  'Grand Est': 7.0,
  'Hauts-de-France': 6.0,
  'Normandy': 6.0,
  'Brittany': 4.0,
  'Auvergne-Rhone-Alpes': 4.0,
  "Provence-Alpes-Cote d'Azur": 4.0,
  'Ile-de-France': 2.0,
  'Corsica': 1.0,
  'Centre': 1.0,
  'Nord-Pas-de-Calais': 1.0,
  'Alsace': 1.0,
  'Paca': 1.0,
  'Champagne-Ardenne': 1.0},


 'Uruguay':{
     'Artigas':8,
     'Cerro Largo':8,
     'Colonia':2,
     'Durazno':8,
     'Flores':8,
     'Florida':7,
     'Lavalleja':8,
     'Paysandu':8,
     'Rio Negro':7,
     'Rivera':7,
     'Salto':7,
     'Soriano':7,
     'Tacuarembo':7,
     'Treinta y Tres':7,
 },
 'Paraguay':{
     'Alto Parana':8,
     'Amambay':8,
     'Caaguazu':8,
     'Caazapa':8,
     'Canindeyu':8,
     'Concepcion':7,
     'Cordillera':8,
     'Guaira':8,
     'Itapua':8,
     'Misiones':8,
     'Neembucu':7,
     'Paraguari':7,
     'San Pedro':7,
 },
 'Bolivia':{
     'Beni':50,
     'Santa Cruz':50},
     
     'Australia': {
        "New South Wales": 100.0},
 
 }
 