# -*- coding: utf-8 -*-
"""
Created on Wed Oct 11 08:54:31 2023

@author: townsend.lansburg
"""



seasons = {
#    "United States of America": {"start_day": 185, "end_day": 245},  # Early July to Late August
  'Brazil':{ 'Maranhao': {"start_day": 330, "end_day": 100},
         'Rio Grande do Sul': {"start_day": 350, "end_day": 75},
         'Parana': {"start_day": 330, "end_day": 45}, 
         'Sao Paulo': {"start_day": 340, "end_day": 80},
         'Minas Gerais': {"start_day": 330, "end_day": 45},
       'Goias': {"start_day": 330, "end_day": 50}, 
       'Mato Grosso': {"start_day": 320, "end_day": 40}, 
       'Mato Grosso do Sul': {"start_day": 330, "end_day": 75}, 
       'Bahia': {"start_day": 330, "end_day": 65}, 
       'Tocantins': {"start_day": 330, "end_day": 65},
       'Santa Catarina': {"start_day": 350, "end_day": 75},
       'Bahia': {"start_day": 330, "end_day": 65},
       'Piaui': {"start_day": 330, "end_day": 65},
       'Federal District': {"start_day": 330, "end_day": 65},
       'Espirito Santo': {"start_day": 330, "end_day": 65},
       'Rio de Janeiro':{"start_day": 330, "end_day": 65},
       'Ceara':{"start_day": 330, "end_day": 65},
       'Rio Grande do Norte':{"start_day": 330, "end_day": 65},
       'Paraiba':{"start_day": 330, "end_day": 65},
       'Pernambuco':{"start_day": 330, "end_day": 65},
       'Alagoas':{"start_day": 330, "end_day": 65},
       'Sergipe':{"start_day": 330, "end_day": 65},
         'Rondonia':{"start_day": 330, "end_day": 65},
          'Acre':{"start_day": 330, "end_day": 65},
          'Amazonas':{"start_day": 330, "end_day": 65},
          'Roraima':{"start_day": 330, "end_day": 65},
          'Amapa':{"start_day": 330, "end_day": 65},
         'Para':{"start_day": 330, "end_day": 65}},
            
'Canada': {'start_day': 165, 'end_day': 279}, 
 'United States of America': {'start_day': 165, 'end_day': 249}, 
 'Mexico': {'start_day': 219, 'end_day': 322}, 
 'Bolivia': {'start_day': 310, 'end_day': 107}, 
 'Colombia': {'start_day': 248, 'end_day': 328},
 'Ecuador': {'start_day': 44, 'end_day': 129}, 
 'Guayana': {'start_day': 186, 'end_day': 317}, 
 'Peru': {'start_day': 345, 'end_day': 105},
 'Venezuela': {'start_day': 337, 'end_day': 78},
 'Paraguay': {'start_day': 331, 'end_day': 71}, 
 'Uruguay': {'start_day': 333, 'end_day': 120}, 
 'Croatia': {'start_day': 150, 'end_day': 251},
 'Hungary': {'start_day': 146, 'end_day': 249}, 
 'Italy': {'start_day': 140, 'end_day': 279}, 
 'Romania': {'start_day': 161, 'end_day': 262},
 'Serbia': {'start_day': 145, 'end_day': 257},
 'Iran': {'start_day': 135, 'end_day': 249},
 'Turkey': {'start_day': 112, 'end_day': 215}, 
 'China': {'start_day': 137, 'end_day': 248}, 
 'Burma': {'start_day': 75, 'end_day': 252}, 
 'Indonesia': {'start_day': 341, 'end_day': 40},
 'Thailand': {'start_day': 165, 'end_day': 249}, 
 'Vietnam': {'start_day': 44, 'end_day': 97}, 
 'North Korea': {'start_day': 122, 'end_day': 232},
 'South Korea': {'start_day': 135, 'end_day': 249}, 
 'Japan': {'start_day': 149, 'end_day': 250},
 'Bangladesh': {'start_day': 351, 'end_day': 96}, 
 'India': {'start_day': 196, 'end_day': 249}, 
 'Egypt': {'start_day': -8, 'end_day': 185}, 
 'South Africa': {'start_day': 331, 'end_day': 104}, 
 'Zambia': {'start_day': 339, 'end_day': 110}, 
 'Ethiopia': {'start_day': 196, 'end_day': 279}, 
 'Uganda': {'start_day': 227, 'end_day': 310}, 
 'Benin': {'start_day': 179, 'end_day': 262}, 
 'Ghana': {'start_day': 183, 'end_day': 252}, 
 'Nigeria': {'start_day': 196, 'end_day': 252},
 'Argentina': {'start_day': 350, 'end_day': 110}
}





# Dictionary for state-wise production percentages for soybeans

state_production = {
   'United States of America': {'Iowa': 12.0,
  'Illinois': 12.0,
  'Minnesota': 11.0,
  'Nebraska': 9.0,
  'Indiana': 7.0,
  'Missouri': 6.0,
  'Ohio': 5.0,
  'South Dakota': 5.0,
  'North Dakota': 4.0,
  'Arkansas': 3.0,
  'Mississippi': 3.0,
  'Kansas': 2.0,
  'Louisiana': 2.0,
  'Michigan': 2.0,
  'Kentucky': 1.0,
  'Tennessee': 1.0,
  'Wisconsin': 1.0,
  'Alabama': 1.0,
  'Texas': 1.0},
 
    'Brazil': {'Mato Grosso': 29.0,
  'Parana': 18.0,
  'Rio Grande do Sul': 14.0,
  'Goias': 8.0,
  'Mato Grosso do Sul': 7.0,
  'Bahia': 6.0,
  'Sao Paulo': 4.0,
  'Minas Gerais': 3.0,
  'Maranhao': 1.0,
  'Tocantins': 1.0, 
    'Santa Catarina': 5.0,
    'Bahia': 3.0,
    'Piaui': 1.0,
    'Federal District': 0.3,
    'Espirito Santo': 0.1,
    'Rio de Janeiro':0.001,
    'Ceara':2.5,
    'Rio Grande do Norte':0.2,
    'Paraiba':0.5,
    'Pernambuco':0.9,
    'Alagoas':0.2,
    'Sergipe':0.8,
      'Rondonia':1.3,
       'Acre':0.2,
       'Amazonas':0.00001,
       'Roraima':0.1,
       'Amapa':0.001,
      'Para':1.8,},
 
    'Argentina': {'Buenos Aires': 32.0,
  'Santa Fe': 28.0,
  'Cordoba': 28.0,
  'Entre Rios': 8.0,
  'La Pampa': 4.0,
  # 'Santiago del Estero': 4.0,
  # 'San Luis': 2.0,
  # 'Tucuman': 1.0,
  # 'Chaco': 1.0,
  # 'Formosa': 1.0
  },

 'China': {'Heilongjiang': 12.0,
  'Jilin': 10.0,
  'Inner Mongolia': 9.0,
  'Liaoning': 8.0,
  'Hebei': 6.0,
  'Shandong': 6.0,
  'Henan': 5.0,
  'Anhui': 5.0,
  'Hubei': 4.0,
  'Jiangsu': 4.0,
  'Shanxi': 3.0,
  'Jiangxi': 3.0,
  'Gansu': 2.0,
  'Guangdong': 2.0,
  'Sichuan': 1.0,
  'Fujian': 1.0,
  'Yunnan': 1.0},
 
           'India': {'Madhya Pradesh': 35.0,
  'Maharashtra': 20.0,
  'Rajasthan': 8.0,
  'Karnataka': 7.0,
  'Andhra Pradesh': 6.0,
  'Telangana': 5.0,
  'Chhattisgarh': 5.0,
  'Gujarat': 4.0,
  'Tamil Nadu': 3.0,
  'Haryana': 2.0,
  'Uttar Pradesh': 2.0,
  'Odisha': 1.0},
 
          'Paraguay': {'Itapua': 28.0,
  'Canindeyu': 18.0,
  'San Pedro': 13.0,
  'Caaguazu': 12.0,
  'Alto Parana': 10.0,
  'Caazapa': 6.0,
  'Paraguari': 5.0,
  'Guaira': 4.0,
  'Amambay': 2.0,},
 
    'Canada': {'Manitoba': 33.0,
  'Saskatchewan': 29.0,
  'Alberta': 15.0,
  'Ontario': 9.0,
  'Quebec': 5.0,
  'New Brunswick': 2.0,
  'British Columbia': 1.0,
  'Prince Edward Island': 1.0},
 
    'Uruguay': {'Soriano': 28.0,
  'Colonia': 22.0,
  'Rio Negro': 12.0,
  'San Jose': 10.0,
  'Paysandu': 8.0,
  'Treinta y Tres': 6.0,
  'Durazno': 4.0,
  'Canelones': 4.0,
  'Artigas': 2.0,
  'Florida': 2.0},
 
    'Russia': {'Krasnodar Krai': 12.0,
  'Stavropol Krai': 11.0,
  'Belgorod Oblast': 9.0,
  'Voronezh Oblast': 8.0,
  'Rostov Oblast': 7.0,
  'Saratov Oblast': 6.0,
  'Orel Oblast': 5.0,
  'Kursk Oblast': 4.0,
  'Amur Oblast': 4.0,
  'Lipetsk Oblast': 3.0,
  'Kirov Oblast': 3.0,
  'Tambov Oblast': 2.0,
  'Kostroma Oblast': 2.0,
  'Nizhny Novgorod Oblast': 1.0,
  'Penza Oblast': 1.0,
  'Altai Krai': 1.0,
  'Tyumen Oblast': 1.0,
  'Samara Oblast': 1.0,
  'Kurgan Oblast': 1.0},
 
    'Bolivia': {'Santa Cruz': 75.0,
  'Beni': 25.0,},
                
                             "Australia": {
        "Queensland": 100.0},
        
        
 }
 
 
 