# -*- coding: utf-8 -*-
"""
Created on Thu Oct 19 08:42:02 2023

@author: townsend.lansburg
"""



seasons = {
'Colombia': {'start_day': 101, 'end_day': 170}, 
 'Ecuador': {'start_day': 70, 'end_day': 134}, 
 'Peru': {'start_day': 31, 'end_day': 115},
 'Paraguay': {'start_day': 150, 'end_day': 259},
 'Uruguay': {'start_day': 212, 'end_day': 317},
 'Jordan': {'start_day': 65, 'end_day': 154}, 
 'Iran': {'start_day': 283, 'end_day': 157}, 
 'Iraq': {'start_day': 344, 'end_day': 124},
 'Lebanon': {'start_day': 330, 'end_day': 162},
 'Syria': {'start_day': 341, 'end_day': 155}, 
 'Saudi Arabia': {'start_day': 335, 'end_day': 107},
 'Yemen': {'start_day': 173, 'end_day': 246}, 
 'Afghanistan': {'start_day': 331, 'end_day': 140}, 
 'Uzbekistan': {'start_day': 294, 'end_day': 158}, 
 'Burma': {'start_day': 334, 'end_day': 54},
 'South Korea': {'start_day': 302, 'end_day': 154},
 'Australia': {'start_day': 158, 'end_day': 336},
 'Bangladesh': {'start_day': 300, 'end_day': 78},
 'Nepal': {'start_day': 330, 'end_day': 83}, 
 'Egypt': {'start_day': 314, 'end_day': 112}, 
 'Angola': {'start_day': 143, 'end_day': 276}, 
 'Botswana': {'start_day': 143, 'end_day': 276}, 
 'Eswatini': {'start_day': 143, 'end_day': 307}, 
 'Lesotho': {'start_day': 143, 'end_day': 307}, 
 'Madagascar ': {'start_day': 143, 'end_day': 307},
 'Malawi': {'start_day': 62, 'end_day': 195}, 
 'Mozambique': {'start_day': 143, 'end_day': 276},
 'Namibia': {'start_day': 153, 'end_day': 277}, 
 'South Africa': {'start_day': 153, 'end_day': 279},
 'Zambia': {'start_day': 153, 'end_day': 277}, 
 'Zimbabwe': {'start_day': 165, 'end_day': 277},
 'Eritrea': {'start_day': 204, 'end_day': 323},
 'Kenya': {'start_day': 169, 'end_day': 279},
 'Sudan': {'start_day': 326, 'end_day': 62}, 
 'Mali': {'start_day': 349, 'end_day': 40}, 
 'Nigeria': {'start_day': 353, 'end_day': 64},
 'Argentina': {'start_day': 193, 'end_day': 326}
    }



seasons_spring = {
    'Canada': {'start_day': 165, 'end_day': 221},
 'United States of America': {'start_day': 135, 'end_day': 218},
 'Bolivia': {'start_day': 135, 'end_day': 256}, 
 'Denmark': {'start_day': 135, 'end_day': 220},
 'Estonia': {'start_day': 135, 'end_day': 227}, 
 'Finland': {'start_day': 135, 'end_day': 227}, 
 'Ireland': {'start_day': 106, 'end_day': 218}, 
 'Italy': {'start_day': 104, 'end_day': 187}, 
 'Latvia': {'start_day': 135, 'end_day': 223}, 
 'Lithuania': {'start_day': 135, 'end_day': 223},
 'Luxembourg': {'start_day': 135, 'end_day': 232}, 
 'Netherlands': {'start_day': 135, 'end_day': 219}, 
 'Spain': {'start_day': 104, 'end_day': 202}, 
 'Sweden': {'start_day': 147, 'end_day': 217}, 
 'United Kingdom': {'start_day': 106, 'end_day': 218},
 'Russia': {'start_day': 143, 'end_day': 225},
 'Azerbaijan': {'start_day': 104, 'end_day': 187}, 
 'Turkey': {'start_day': 104, 'end_day': 187}, 
 'Kyrgyzstan': {'start_day': 135, 'end_day': 249},
 'Tajikistan': {'start_day': 158, 'end_day': 218}, 
 'China': {'start_day': 105, 'end_day': 231}, 
 'North Korea': {'start_day': 82, 'end_day': 154}, 
 'New Zealand': {'start_day': 275, 'end_day': 63}, 
 'Ethiopia': {'start_day': 196, 'end_day': 282},
 }



seasons_winter = {
'Canada': {'start_day': 311, 'end_day': 187}, 
 'United States of America': {'start_day': 288, 'end_day': 187},
 'Mexico': {'start_day': 16, 'end_day': 102},
 'Brazil ': {'start_day': 165, 'end_day': 282},
 'Bolivia': {'start_day': 341, 'end_day': 109}, 
 'Albania': {'start_day': 326, 'end_day': 157}, 
 'Austria': {'start_day': 288, 'end_day': 173},
 'Belgium': {'start_day': 288, 'end_day': 173},
 'Bosnia and Herzegovina': {'start_day': 288, 'end_day': 173}, 
 'Bulgaria': {'start_day': 288, 'end_day': 173},
 'Cyprus': {'start_day': 351, 'end_day': 143}, 
 'Denmark': {'start_day': 296, 'end_day': 200},
 'Estonia': {'start_day': 266, 'end_day': 186},
 'Croatia': {'start_day': 288, 'end_day': 173},
 'Czech Republic': {'start_day': 288, 'end_day': 173},
 'Finland': {'start_day': 269, 'end_day': 185}, 
 'France': {'start_day': 313, 'end_day': 173},
 'Germany': {'start_day': 288, 'end_day': 187}, 
 'Hungary': {'start_day': 288, 'end_day': 173},
 'Ireland': {'start_day': 318, 'end_day': 187},
 'Italy': {'start_day': 288, 'end_day': 173}, 
 'Latvia': {'start_day': 270, 'end_day': 185}, 
 'Lithuania': {'start_day': 270, 'end_day': 185},
 'Luxembourg': {'start_day': 288, 'end_day': 173}, 
 'North Macedonia': {'start_day': 326, 'end_day': 157},
 'Malta': {'start_day': 288, 'end_day': 168}, 
 'Netherlands': {'start_day': 288, 'end_day': 173},
 'Norway': {'start_day': 288, 'end_day': 173}, 
 'Portugal': {'start_day': 288, 'end_day': 173}, 
 'Poland': {'start_day': 288, 'end_day': 187},
 'Romania': {'start_day': 288, 'end_day': 173},
 'Serbia': {'start_day': 302, 'end_day': 171},
 'Slovakia': {'start_day': 288, 'end_day': 173},
 'Spain': {'start_day': 349, 'end_day': 146},
 'Slovenia': {'start_day': 288, 'end_day': 173},
 'Sweden': {'start_day': 288, 'end_day': 157}, 
 'Switzerland': {'start_day': 288, 'end_day': 173},
 'United Kingdom': {'start_day': 318, 'end_day': 187},
 'Russia': {'start_day': 250, 'end_day': 190},
 'Belarus': {'start_day': 265, 'end_day': 185}, 
 'Moldova': {'start_day': 249, 'end_day': 193},
 'Ukraine': {'start_day': 246, 'end_day': 188},
 'Armenia': {'start_day': 280, 'end_day': 129},
 'Azerbaijan': {'start_day': 349, 'end_day': 157},
 'Georgia': {'start_day': 284, 'end_day': 185}, 
 'Turkey': {'start_day': 318, 'end_day': 187}, 
 'Kyrgyzstan': {'start_day': 242, 'end_day': 158},
 'Tajikistan': {'start_day': 294, 'end_day': 158}, 
 'Turkmenistan': {'start_day': 294, 'end_day': 185},
 'China': {'start_day': 293, 'end_day': 142}, 
 'North Korea': {'start_day': 306, 'end_day': 154}, 
 'Japan': {'start_day': 312, 'end_day': 146},
 'New Zealand': {'start_day': 126, 'end_day': 18},
 'Pakistan': {'start_day': 329, 'end_day': 97},
 'Algeria': {'start_day': 330, 'end_day': 140}, 
 'Libya': {'start_day': 330, 'end_day': 135}, 
 'Morocco': {'start_day': 335, 'end_day': 116},
 'Tunisia': {'start_day': 335, 'end_day': 137}, 
 'Ethiopia': {'start_day': 349, 'end_day': 62},
 }


# Dictionary for state-wise production percetanges for wheat

state_production = {
    "China": {
        "Henan": 15.0,
        "Shandong": 13.0,
        "Hebei": 10.0,
        "Anhui": 9.0,
        "Jiangsu": 8.0,
        "Hubei": 6.0,
        "Sichuan": 6.0,
        "Shaanxi": 5.0,
        "Jiangxi": 4.0,
        "Heilongjiang": 4.0,
        "Liaoning": 3.0,
        "Guangdong": 3.0,
        "Hunan": 2.0,
        "Yunnan": 2.0,
        "Inner Mongolia": 2.0,
        "Fujian": 1.0,
        "Shanxi": 1.0,
        "Guangxi": 1.0,
        "Gansu": 1.0,
        "Hainan": 1.0,
    },
    "India": {
        "Uttar Pradesh": 28.0,
        "Punjab": 19.0,
        "Madhya Pradesh": 14.0,
        "Haryana": 12.0,
        "Rajasthan": 10.0,
        "Bihar": 3.0,
        "Gujarat": 2.0,
        "West Bengal": 2.0,
        "Assam": 2.0,
        "Odisha": 1.0,
        "Jharkhand": 1.0,
        "Maharashtra": 1.0,
        "Himachal Pradesh": 1.0,
        "Chhattisgarh": 1.0,
    },
    "Russia": {
        "Krasnodar Krai": 11.0,
        "Rostov Oblast": 9.0,
        "Altai Krai": 9.0,
        "Bashkortostan": 8.0,
        "Siberian Federal District": 8.0,
        "Omsk Oblast": 6.0,
        "Tyumen Oblast": 6.0,
        "Kurgan Oblast": 5.0,
        "Chelyabinsk Oblast": 5.0,
        "Novosibirsk Oblast": 4.0,
        "Orenburg Oblast": 3.0,
        "Sverdlovsk Oblast": 3.0,
        "Kemerovo Oblast": 3.0,
        "Tomsk Oblast": 2.0,
        "Irkutsk Oblast": 2.0,
        "Altai Republic": 1.0,
        "Khakassia": 1.0,
        "Novgorod Oblast": 1.0,
        "Kirov Oblast": 1.0,
        "Amur Oblast": 1.0,
    },
    "United States of America": {
        "North Dakota": 13.0,
        "Montana": 12.0,
        "Kansas": 9.0,
        "Washington": 7.0,
        "Oklahoma": 7.0,
        "South Dakota": 7.0,
        "Idaho": 6.0,
        "Minnesota": 5.0,
        "Texas": 5.0,
        "Colorado": 5.0,
        "Nebraska": 5.0,
        "Oregon": 4.0,
        "Michigan": 3.0,
        "California": 3.0,
        "Iowa": 2.0,
        "Ohio": 2.0,
        "Wisconsin": 2.0,
        "Indiana": 1.0,
        "Illinois": 1.0,
        "Arizona": 1.0,
        "North Carolina": 1.0,
        "Florida": 1.0,
        "New York": 1.0,
    },
    "Canada": {
        "Saskatchewan": 38.0,
        "Alberta": 23.0,
        "Manitoba": 18.0,
        "Ontario": 12.0,
        "Quebec": 4.0,
        "British Columbia": 2.0,
        "New Brunswick": 1.0,
        "Nova Scotia": 1.0,
    },
    "Pakistan": {
        "Punjab": 71.0,
        "Sindh": 17.0,
        "Khyber Pakhtunkhwa": 7.0,
        "Balochistan": 3.0,
        "Azad Jammu and Kashmir": 1.0,
        "Gilgit-Baltistan": 1.0,
    },
    "Australia": {
        "New South Wales": 32.0,
        "Western Australia": 29.0,
        "South Australia": 19.0,
        "Victoria": 10.0,
        "Queensland": 9.0,
        "Tasmania": 1.0,
    },
    "Ukraine": {
        "Vinnytsia": 12.0,
        "Kharkiv": 11.0,
        "Poltava": 10.0,
        "Odessa": 7.0,
        "Kherson": 7.0,
        "Dnipropetrovsk": 6.0,
        "Zaporizhzhia": 6.0,
        "Zhytomyr": 5.0,
        "Sumy": 5.0,
        "Chernihiv": 4.0,
        "Kirovohrad": 4.0,
        "Ternopil": 3.0,
        "Kyiv": 2.0,
        "Lviv": 2.0,
        "Mykolaiv": 2.0,
        "Khmelnytskyi": 2.0,
        "Chernivtsi": 1.0,
        "Rivne": 1.0,
        "Ivano-Frankivsk": 1.0,
        "Volyn": 1.0,
    },
    "Argentina": {
        "Buenos Aires": 31.0,
        "Cordoba": 17.0,
        "Santa Fe": 12.0,
        "La Pampa": 9.0,
        "Entre Rios": 9.0,
        "Santiago del Estero": 6.0,
        "San Luis": 5.0,
        "Chaco": 5.0,
        "Tucuman": 4.0,
        "Salta": 1.0,
        "Formosa": 1.0,
        "Corrientes": 1.0,
    },
              'Uruguay':{
     'Artigas':8,
     'Cerro Largo':8,
     'Colonia':2,
     'Durazno':8,
     'Flores':8,
     'Florida':7,
     'Lavalleja':8,
     'Paysandu':8,
     'Rio Negro':7,
     'Rivera':7,
     'Salto':7,
     'Soriano':7,
     'Tacuarembo':7,
     'Treinta y Tres':7,
 },
 'Paraguay':{
     'Alto Parana':8,
     'Amambay':8,
     'Caaguazu':8,
     'Caazapa':8,
     'Canindeyu':8,
     'Concepcion':7,
     'Cordillera':8,
     'Guaira':8,
     'Itapua':8,
     'Misiones':8,
     'Neembucu':7,
     'Paraguari':7,
     'San Pedro':7,
 },
 'Bolivia':{
     'Beni':50,
     'Santa Cruz':50,},
         
         'Brazil': {'Mato Grosso': 2.0,
  'Goias': 4.0,
  'Minas Gerais': 4.0,
  'Parana': 44.0,
  'Sao Paulo': 7.0,
  'Rio Grande do Sul': 39.0,
  'Santa Catarina': 39.0,
  },
     
}